version: "3"

services:
  postgres_dev:
    image: postgres:alpine
    container_name: database_dev
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d main -h postgres_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend_dev:
    build: ./backend
    container_name: backend_dev
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - ./backend:/app
    command: bash
    tty: true
    stdin_open: true
    depends_on:
      postgres_dev:
        condition: service_healthy
  frontend_env:
    command: bash
    tty: true
    stdin_open: true
    build: ./frontend
    container_name: frontend_dev
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/site
volumes:
  pgdata: